markdown        : redcarpet
title           : - хмарний файловий менеджер
tagLine         : Хмарний файловий менеджер з консоллю та редактором
viewOn          : Подивитись на
download        : Завантажити
maintainedBy    : Проект підтримує
yandex          : 5c03543d552e9150
