markdown      : redcarpet2
redcarpet:
  extensions: ["with_toc_data"]
tagLine       : Хмарний файловий менеджер з консоллю та редактором
viewOn        : Подивитись на
download      : Завантажити
maintainedBy  : Проект підтримує
