markdown        : redcarpet
name            : Cloud Commander
title           : "Cloud Commander - хмарний файловий менеджер"
tagLine         : Хмарний файловий менеджер з консоллю та редактором
viewOn          : Подивитись на
download        : Завантажити
maintainedBy    : Проект підтримує
yandex          : 5c03543d552e9150
ga              : UA-45093573-4
canonical       : ua.cloudcmd.io
repoName        : cloudcmd/ua/edit/master/last.md
improveText     : "Знайшли помилку? Допоможіть її виправити."
repoSource      : coderaiser/cloudcmd
image           : //cloudcmd.io/img/logo/cloudcmd.png
favicon         : //cloudcmd.io/img/favicon/favicon.png
