markdown        : redcarpet
title           : "Cloud Commander - хмарний файловий менеджер"
tagLine         : Хмарний файловий менеджер з консоллю та редактором
viewOn          : Подивитись на
download        : Завантажити
maintainedBy    : Проект підтримує
yandex          : 5c03543d552e9150
ga              : UA-45093573-4
canonical       : ua.cloudcmd.io
repoName        : cloudcmd/io-ua/edit/gh-pages/index.md
improveText     : "Знайшли помилку? Допоможіть її виправити."
